### ISSUE TITLE
Can't get the digital value

### ISSUE THREAD

**Issue by coding-lifev** [qualiaa/haxe_arduino#2]
It always returns "Null"
But,the pin is high.
How should I do?
` bridge.setDigitalPin(12,HIGH);
        trace(bridge.getDigitalPin(12));`

**Comment by dixonary** [comment]
getDigitalPin is used for reading a digital input, I believe. You will have
to store the output stage locally.

**Comment by coding-lifev** [comment]
@ dixonary
OK,now,I use requestDigitalPin to solve it.
